name: Core Preview GH Pages

on:
  workflow_dispatch:
  push:
    branches: [firebolt-core]

jobs:
  mirror:
    name: Mirror only from staging repo
    if: github.repository == 'firebolt-analytics/firebolt-docs-staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.FB_DB_CI_WRITER_ID }}
          private-key: ${{ secrets.FB_DB_CI_WRITER_PEM }}
          owner: firebolt-db
      - name: Push to preview main branch (firebolt-db)
        run: |
          git remote add preview1 https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/firebolt-db/firebolt-docs-preview-core.git
          git push preview1 HEAD:main --force

          echo "Preview documentation is available at: https://old.docs.firebolt.io/firebolt-docs-preview-core/FireboltCore/" >> $GITHUB_STEP_SUMMARY
