name: "Lint PR"

on:
  pull_request:
    branches:
      - gh-pages
      - release/packdb-*
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr_conventions:
    uses: firebolt-analytics/gha-workflows/.github/workflows/conventional_pr.yaml@4b4ef721cfc2b0b3682a90a83db3bbad73008a5a  # v2.46.0
