name: Mirror GH Pages

on:
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror
    if: github.repository == 'firebolt-analytics/firebolt-docs-staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: gh-pages
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.FB_DB_CI_WRITER_ID }}
          private-key: ${{ secrets.FB_DB_CI_WRITER_PEM }}
          owner: firebolt-db
      - name: Mirror
        run: |
          git remote add public https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/firebolt-db/godocs.git
          git push public gh-pages
