name: Check PR before merge
on:
  pull_request:
    branches:
    - '**'

jobs:
  check-basic-errors:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      issues: read
      # permission needed to post a comment on the PR
      pull-requests: write
    outputs:
      output: ${{ steps.check-nav.outputs.output }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493  # v4.2.2

      - name: Check for merge conflict markers
        run: make check-markers

      - name: Check that /docs directory does not exist
        run: make check-legacy-dir

      - name: Check navigation sanity
        id: check-nav
        run: |
          set -euo pipefail
          scripts/run-check-gha.sh \
            "Navigation Consistency Checks" required \
            make check-navigation | tee -a $GITHUB_OUTPUT | tail -n +2 | head -n -1 >> "$GITHUB_STEP_SUMMARY" 

  check-broken-links:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      issues: read
      # permission needed to post a comment on the PR
      pull-requests: write
    outputs:
      output: ${{ steps.check-links-mint.outputs.output }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493  # v4.2.2

      - name: Check there are no 404 links
        id: check-links-mint
        run: |
          set -euo pipefail
          scripts/run-check-gha.sh \
            "Link Check (internal)" "" \
            make check-internal-links | tee -a $GITHUB_OUTPUT | tail -n +2 | head -n -1 >> "$GITHUB_STEP_SUMMARY" 

  check-links-using-crawler:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      issues: read
      # permission needed to post a comment on the PR
      pull-requests: write
    outputs:
      output: ${{ steps.check-links-crawler.outputs.output }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493  # v4.2.2

      - name: Check there are no 404 links
        id: check-links-crawler
        run: |
          set -euo pipefail
          (scripts/run-check-gha.sh \
            "Link Check (crawler)" informational \
            make check-links-using-crawler || true) | tee -a $GITHUB_OUTPUT | tail -n +2 | head -n -1 >> "$GITHUB_STEP_SUMMARY"

  check-sql-examples:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      issues: read
      # permission needed to post a comment on the PR
      pull-requests: write
    outputs:
      output: ${{ steps.check-sql.outputs.output }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493  # v4.2.2

      - name: Check SQL examples
        id: check-sql
        run: |
          set -euo pipefail
          (scripts/run-check-gha.sh \
            "SQL Example Check" informational \
            make check-sql || true) | tee -a $GITHUB_OUTPUT | tail -n +2 | head -n -1 >> "$GITHUB_STEP_SUMMARY" 

  summarize_results:
    needs:
      - check-basic-errors
      - check-broken-links
      - check-links-using-crawler
      - check-sql-examples
    runs-on: ubuntu-24.04
    if: always()
    steps:
      - name: Find Comment
        id: fc-summary
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e  # v3.1.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Check Summary"

      - name: Post a comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043  # v4.0.0
        if: always()
        with:
          comment-id: ${{ steps.fc-summary.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            #### Check Summary
            ${{ needs.check-basic-errors.outputs.output }}
            ${{ needs.check-broken-links.outputs.output }}
            ${{ needs.check-links-using-crawler.outputs.output }}
            ${{ needs.check-sql-examples.outputs.output }}
          edit-mode: replace
