name: Validate SQL/JSON pairs

on:
  pull_request:
    paths:
      - 'docs/_includes/sql_examples/**'

jobs:
  validate-pairs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Need full history to compare changes

    - name: Check modified SQL files have updated JSON
      id: check-sql-json
      run: |
        cd docs/_includes/sql_examples
        error=0
        # Initialize an empty file for our output
        touch temp_output.txt
        
        # Get list of modified SQL files in this PR
        modified_sql=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep '\.sql$' || true)
        
        for sql in $modified_sql; do
          base_name=$(basename "$sql")
          json_name="${base_name%.sql}.json"
          
          # Check if corresponding JSON was also modified
          if ! git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep -q "$json_name"; then
            echo "Error: $base_name was modified but $json_name was not updated" >> temp_output.txt
            error=1
          fi
        done
        
        # Set the error status and validation output as separate outputs
        echo "error=$error" >> $GITHUB_OUTPUT
        echo "output<<EOF" >> $GITHUB_OUTPUT
        cat temp_output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Find SQL Validation Comment
      id: find-sql-validation
      uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e  # v3.1.0
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "SQL/JSON Validation Status:"


    - name: Post validation failure comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043  # v4.0.0
      with:
        comment-id: ${{ steps.find-sql-validation.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          # $\color{red}{\text{❌ SQL/JSON Validation Status: FAILURE}}$
          Please run `make package-missing-docs` to update the missing SQL/JSON pairs.

          ```
          ${{ steps.check-sql-json.outputs.output }}
          ```
        edit-mode: replace


    - name: Post validation success comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043  # v4.0.0
      if: github.event_name == 'pull_request' && steps.check-sql-json.outputs.error == 0
      with:
        comment-id: ${{ steps.find-sql-validation.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          # $\color{green}{\text{✅ SQL/JSON Validation Status: SUCCESS}}$
        edit-mode: replace

    - name: Exit with error if validation failed
      if: steps.check-sql-json.outputs.error == 1
      run: exit 1